#next-version: 1.0.0
mode: ContinuousDeployment
assembly-versioning-scheme: MajorMinorPatchTag
assembly-informational-format: '{SemVer}+{ShortSha}'
branches:
  main:
    regex: ^main$
    source-branches: [ 'release', 'feature' ]
    tag: pre