//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Wpf.TestApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestAppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestAppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Wpf.TestApp.Resources.TestAppResources", typeof(TestAppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boutons.
        /// </summary>
        internal static string Buttons {
            get {
                return ResourceManager.GetString("Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendriers.
        /// </summary>
        internal static string Calendars {
            get {
                return ResourceManager.GetString("Calendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        internal static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteneurs.
        /// </summary>
        internal static string Containers {
            get {
                return ResourceManager.GetString("Containers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates et Heures.
        /// </summary>
        internal static string DateAndTimes {
            get {
                return ResourceManager.GetString("DateAndTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Défaut.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropDownButtons.
        /// </summary>
        internal static string DropDownButtons {
            get {
                return ResourceManager.GetString("DropDownButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs.
        /// </summary>
        internal static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupBoxes.
        /// </summary>
        internal static string GroupBoxes {
            get {
                return ResourceManager.GetString("GroupBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icônes.
        /// </summary>
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu offensif axial.
        /// </summary>
        internal static string PositionCenterAttackingMidfielder {
            get {
                return ResourceManager.GetString("PositionCenterAttackingMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOC.
        /// </summary>
        internal static string PositionCenterAttackingMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionCenterAttackingMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Défenseur central.
        /// </summary>
        internal static string PositionCenterBack {
            get {
                return ResourceManager.GetString("PositionCenterBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC.
        /// </summary>
        internal static string PositionCenterBackAbbr {
            get {
                return ResourceManager.GetString("PositionCenterBackAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu offensif.
        /// </summary>
        internal static string PositionCenterLeftAttackingMidfielder {
            get {
                return ResourceManager.GetString("PositionCenterLeftAttackingMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MO.
        /// </summary>
        internal static string PositionCenterLeftAttackingMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionCenterLeftAttackingMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Défenseur central.
        /// </summary>
        internal static string PositionCenterLeftBack {
            get {
                return ResourceManager.GetString("PositionCenterLeftBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC.
        /// </summary>
        internal static string PositionCenterLeftBackAbbr {
            get {
                return ResourceManager.GetString("PositionCenterLeftBackAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu axial.
        /// </summary>
        internal static string PositionCenterLeftMidfielder {
            get {
                return ResourceManager.GetString("PositionCenterLeftMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        internal static string PositionCenterLeftMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionCenterLeftMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu axial.
        /// </summary>
        internal static string PositionCenterMidfielder {
            get {
                return ResourceManager.GetString("PositionCenterMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        internal static string PositionCenterMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionCenterMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu offensif.
        /// </summary>
        internal static string PositionCenterRightAttackingMidfielder {
            get {
                return ResourceManager.GetString("PositionCenterRightAttackingMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MO.
        /// </summary>
        internal static string PositionCenterRightAttackingMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionCenterRightAttackingMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Défenseur central.
        /// </summary>
        internal static string PositionCenterRightBack {
            get {
                return ResourceManager.GetString("PositionCenterRightBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC.
        /// </summary>
        internal static string PositionCenterRightBackAbbr {
            get {
                return ResourceManager.GetString("PositionCenterRightBackAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu axial.
        /// </summary>
        internal static string PositionCenterRightMidfielder {
            get {
                return ResourceManager.GetString("PositionCenterRightMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        internal static string PositionCenterRightMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionCenterRightMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu défensif.
        /// </summary>
        internal static string PositionDefensiveLeftMidfielder {
            get {
                return ResourceManager.GetString("PositionDefensiveLeftMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD.
        /// </summary>
        internal static string PositionDefensiveLeftMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionDefensiveLeftMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu défensif.
        /// </summary>
        internal static string PositionDefensiveMidfielder {
            get {
                return ResourceManager.GetString("PositionDefensiveMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDC.
        /// </summary>
        internal static string PositionDefensiveMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionDefensiveMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu défensif.
        /// </summary>
        internal static string PositionDefensiveRightMidfielder {
            get {
                return ResourceManager.GetString("PositionDefensiveRightMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD.
        /// </summary>
        internal static string PositionDefensiveRightMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionDefensiveRightMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaquant.
        /// </summary>
        internal static string PositionForward {
            get {
                return ResourceManager.GetString("PositionForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATT.
        /// </summary>
        internal static string PositionForwardAbbr {
            get {
                return ResourceManager.GetString("PositionForwardAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardien.
        /// </summary>
        internal static string PositionGoalKeeper {
            get {
                return ResourceManager.GetString("PositionGoalKeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string PositionGoalKeeperAbbr {
            get {
                return ResourceManager.GetString("PositionGoalKeeperAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu offensif gauche.
        /// </summary>
        internal static string PositionLeftAttackingMidfielder {
            get {
                return ResourceManager.GetString("PositionLeftAttackingMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOG.
        /// </summary>
        internal static string PositionLeftAttackingMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionLeftAttackingMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaquant.
        /// </summary>
        internal static string PositionLeftForward {
            get {
                return ResourceManager.GetString("PositionLeftForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATT.
        /// </summary>
        internal static string PositionLeftForwardAbbr {
            get {
                return ResourceManager.GetString("PositionLeftForwardAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrière gauche.
        /// </summary>
        internal static string PositionLeftFullBack {
            get {
                return ResourceManager.GetString("PositionLeftFullBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DG.
        /// </summary>
        internal static string PositionLeftFullBackAbbr {
            get {
                return ResourceManager.GetString("PositionLeftFullBackAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu gauche.
        /// </summary>
        internal static string PositionLeftMidfielder {
            get {
                return ResourceManager.GetString("PositionLeftMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MG.
        /// </summary>
        internal static string PositionLeftMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionLeftMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latéral gauche.
        /// </summary>
        internal static string PositionLeftWingBack {
            get {
                return ResourceManager.GetString("PositionLeftWingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LG.
        /// </summary>
        internal static string PositionLeftWingBackAbbr {
            get {
                return ResourceManager.GetString("PositionLeftWingBackAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ailier gauche.
        /// </summary>
        internal static string PositionLeftWinger {
            get {
                return ResourceManager.GetString("PositionLeftWinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AG.
        /// </summary>
        internal static string PositionLeftWingerAbbr {
            get {
                return ResourceManager.GetString("PositionLeftWingerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poste(s).
        /// </summary>
        internal static string PositionOptionalPlural {
            get {
                return ResourceManager.GetString("PositionOptionalPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peu convaincant.
        /// </summary>
        internal static string PositionRatingAverage {
            get {
                return ResourceManager.GetString("PositionRatingAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        internal static string PositionRatingGood {
            get {
                return ResourceManager.GetString("PositionRatingGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inneficace.
        /// </summary>
        internal static string PositionRatingInefficient {
            get {
                return ResourceManager.GetString("PositionRatingInefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturel.
        /// </summary>
        internal static string PositionRatingNatural {
            get {
                return ResourceManager.GetString("PositionRatingNatural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mal à l&apos;aise.
        /// </summary>
        internal static string PositionRatingPoor {
            get {
                return ResourceManager.GetString("PositionRatingPoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accompli.
        /// </summary>
        internal static string PositionRatingVeryGood {
            get {
                return ResourceManager.GetString("PositionRatingVeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu offensif droit.
        /// </summary>
        internal static string PositionRightAttackingMidfielder {
            get {
                return ResourceManager.GetString("PositionRightAttackingMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOD.
        /// </summary>
        internal static string PositionRightAttackingMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionRightAttackingMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaquant.
        /// </summary>
        internal static string PositionRightForward {
            get {
                return ResourceManager.GetString("PositionRightForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATT.
        /// </summary>
        internal static string PositionRightForwardAbbr {
            get {
                return ResourceManager.GetString("PositionRightForwardAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrière droit.
        /// </summary>
        internal static string PositionRightFullBack {
            get {
                return ResourceManager.GetString("PositionRightFullBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD.
        /// </summary>
        internal static string PositionRightFullBackAbbr {
            get {
                return ResourceManager.GetString("PositionRightFullBackAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu droit.
        /// </summary>
        internal static string PositionRightMidfielder {
            get {
                return ResourceManager.GetString("PositionRightMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD.
        /// </summary>
        internal static string PositionRightMidfielderAbbr {
            get {
                return ResourceManager.GetString("PositionRightMidfielderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latéral droit.
        /// </summary>
        internal static string PositionRightWingBack {
            get {
                return ResourceManager.GetString("PositionRightWingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LD.
        /// </summary>
        internal static string PositionRightWingBackAbbr {
            get {
                return ResourceManager.GetString("PositionRightWingBackAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ailier droit.
        /// </summary>
        internal static string PositionRightWinger {
            get {
                return ResourceManager.GetString("PositionRightWinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD.
        /// </summary>
        internal static string PositionRightWingerAbbr {
            get {
                return ResourceManager.GetString("PositionRightWingerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postes.
        /// </summary>
        internal static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        internal static string PositionSideCenter {
            get {
                return ResourceManager.GetString("PositionSideCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauche.
        /// </summary>
        internal static string PositionSideLeft {
            get {
                return ResourceManager.GetString("PositionSideLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droit.
        /// </summary>
        internal static string PositionSideRight {
            get {
                return ResourceManager.GetString("PositionSideRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libéro.
        /// </summary>
        internal static string PositionSweeper {
            get {
                return ResourceManager.GetString("PositionSweeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string PositionSweeperAbbr {
            get {
                return ResourceManager.GetString("PositionSweeperAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millieu Offensif.
        /// </summary>
        internal static string PositionTypeAttackingMidfielder {
            get {
                return ResourceManager.GetString("PositionTypeAttackingMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Défenseur.
        /// </summary>
        internal static string PositionTypeCenterBack {
            get {
                return ResourceManager.GetString("PositionTypeCenterBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu défensif.
        /// </summary>
        internal static string PositionTypeDefensiveMidfielder {
            get {
                return ResourceManager.GetString("PositionTypeDefensiveMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaquant.
        /// </summary>
        internal static string PositionTypeForward {
            get {
                return ResourceManager.GetString("PositionTypeForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrière.
        /// </summary>
        internal static string PositionTypeFullBack {
            get {
                return ResourceManager.GetString("PositionTypeFullBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardien.
        /// </summary>
        internal static string PositionTypeGoalKeeper {
            get {
                return ResourceManager.GetString("PositionTypeGoalKeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milieu.
        /// </summary>
        internal static string PositionTypeMidfielder {
            get {
                return ResourceManager.GetString("PositionTypeMidfielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buteur.
        /// </summary>
        internal static string PositionTypeStriker {
            get {
                return ResourceManager.GetString("PositionTypeStriker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libéro.
        /// </summary>
        internal static string PositionTypeSweeper {
            get {
                return ResourceManager.GetString("PositionTypeSweeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latéral.
        /// </summary>
        internal static string PositionTypeWingBack {
            get {
                return ResourceManager.GetString("PositionTypeWingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ailier.
        /// </summary>
        internal static string PositionTypeWinger {
            get {
                return ResourceManager.GetString("PositionTypeWinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progression.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgressBars.
        /// </summary>
        internal static string ProgressBars {
            get {
                return ResourceManager.GetString("ProgressBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plannings.
        /// </summary>
        internal static string Schedulers {
            get {
                return ResourceManager.GetString("Schedulers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrollViewers.
        /// </summary>
        internal static string ScrollViewers {
            get {
                return ResourceManager.GetString("ScrollViewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les paramètres ont bien été sauvegardés..
        /// </summary>
        internal static string SettingsHaveBeenSaved {
            get {
                return ResourceManager.GetString("SettingsHaveBeenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliders.
        /// </summary>
        internal static string Sliders {
            get {
                return ResourceManager.GetString("Sliders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SplitButtons.
        /// </summary>
        internal static string SplitButtons {
            get {
                return ResourceManager.GetString("SplitButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabControls.
        /// </summary>
        internal static string TabControls {
            get {
                return ResourceManager.GetString("TabControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thème.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles.
        /// </summary>
        internal static string Toggles {
            get {
                return ResourceManager.GetString("Toggles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traduction.
        /// </summary>
        internal static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typographie.
        /// </summary>
        internal static string Typography {
            get {
                return ResourceManager.GetString("Typography", resourceCulture);
            }
        }
    }
}
