//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Wpf.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WpfResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WpfResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Wpf.Resources.WpfResources", typeof(WpfResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        internal static string AccentColor {
            get {
                return ResourceManager.GetString("AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centrer.
        /// </summary>
        internal static string AlignCenter {
            get {
                return ResourceManager.GetString("AlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justifier.
        /// </summary>
        internal static string AlignJustify {
            get {
                return ResourceManager.GetString("AlignJustify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligner à gauche.
        /// </summary>
        internal static string AlignLeft {
            get {
                return ResourceManager.GetString("AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligner à droite.
        /// </summary>
        internal static string AlignRight {
            get {
                return ResourceManager.GetString("AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleurs disponibles.
        /// </summary>
        internal static string AvailableColors {
            get {
                return ResourceManager.GetString("AvailableColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bleu.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gras.
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminosité.
        /// </summary>
        internal static string Brigthness {
            get {
                return ResourceManager.GetString("Brigthness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puces.
        /// </summary>
        internal static string Bullets {
            get {
                return ResourceManager.GetString("Bullets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diminuer la taille de la police.
        /// </summary>
        internal static string DecreaseFontSize {
            get {
                return ResourceManager.GetString("DecreaseFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diminuer le retrait.
        /// </summary>
        internal static string DecreaseIndentation {
            get {
                return ResourceManager.GetString("DecreaseIndentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police.
        /// </summary>
        internal static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur du texte.
        /// </summary>
        internal static string Foreground {
            get {
                return ResourceManager.GetString("Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vert.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teinte.
        /// </summary>
        internal static string Hue {
            get {
                return ResourceManager.GetString("Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augmenter la taille de la police.
        /// </summary>
        internal static string IncreaseFontSize {
            get {
                return ResourceManager.GetString("IncreaseFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augmenter le retrait.
        /// </summary>
        internal static string IncreaseIndentation {
            get {
                return ResourceManager.GetString("IncreaseIndentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italique.
        /// </summary>
        internal static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numérotation.
        /// </summary>
        internal static string Numbering {
            get {
                return ResourceManager.GetString("Numbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner une couleur sur l&apos;écran.
        /// </summary>
        internal static string PickColorOnScreen {
            get {
                return ResourceManager.GetString("PickColorOnScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur prédéfinies.
        /// </summary>
        internal static string PresetColors {
            get {
                return ResourceManager.GetString("PresetColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primaire.
        /// </summary>
        internal static string PrimaryColor {
            get {
                return ResourceManager.GetString("PrimaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleurs récentes.
        /// </summary>
        internal static string RecentColors {
            get {
                return ResourceManager.GetString("RecentColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rouge.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        internal static string Saturation {
            get {
                return ResourceManager.GetString("Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleurs standards.
        /// </summary>
        internal static string StandardColors {
            get {
                return ResourceManager.GetString("StandardColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparence.
        /// </summary>
        internal static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souligner.
        /// </summary>
        internal static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; n&apos;est pas une couleur valide..
        /// </summary>
        internal static string XIsNotAValidColorError {
            get {
                return ResourceManager.GetString("XIsNotAValidColorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; n&apos;est pas une image valide..
        /// </summary>
        internal static string XIsNotAValidImageError {
            get {
                return ResourceManager.GetString("XIsNotAValidImageError", resourceCulture);
            }
        }
    }
}
